### ISSUE TITLE
Mechanism for controlling plugin & theme activation in code

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/knowledge-commons-wordpress#14]
Create a mechanism for specifying themes and plugins to be activated on base & user sites in code.

## Motivation

Currently plugin and theme activations are controlled solely through the WP Admin interface. Combined with the large number of plugins and themes running on the Commons network, this causes many unintended differences in activations between sites. By specifying this in code, we can have a more reliable and maintainable way of managing themes and plugins across the network. This will also make launching new networks significantly easier, as currently there is significant effort require to configure new networks.

## Implementation

Create a YAML file following the following pattern:

```yaml
default:
    base-site-plugins:
       - hc-custom
       - bbpress
       - classic-widgets
       - ...
    network-plugins:
       - humanities-commons
       - buddypress
       - ...
    allowed-user-plugins:
       - mathml-block
       - zotpress
       - ...
    allowed-user-themes:
       - blockbase
       - twentytwentythree
    base-theme: boss-child
    user-theme: twentytwentythree
mla.hcommons.org:
    base-site-plugins:
       - -classic-widgets
       - hc-auth
    ...
up.hcommons.org:
    ...
commons.msu.edu:
    ...
```

This file first specifies a default configuration with the following properties:

- `base-site-plugins` : Plugins activated on the base site of a network (hcommons.org, mla.hcommons.org, etc)
- `network-plugins` : Plugins network-activated
- `allowed-user-plugins` : Plugins that users are permitted to activate on their sites
- `allowed-user-themes` : Themes that users are permitted to activate on their sites
- `base-theme` : The theme active on the base site.
- `user-theme` : The theme active by default on new user sites.

Networks may override the default settings for each of these. Plugins / themes specified in the list for a property are *added* to the default list, while those prefixed with a `-` are subtracted from the default list.

The constraints specified by the configuration file are enforced when:

- The site is (re)launched
- A new network is created
- A user manages themes or plugins on their site

Already-active plugins & themes on user sites are not affected, so there will be no immediate impact on existing user sites.
